version 6
#delimit ;
set matsize 800;
set more off;
use censeddata.dta;
gen time=csyr-1979;
gen time2=time*time/10;
sort stnum year;
tab stnum, gen(stdum);
***********;
* Predictions:
* generate oldrsup, lnurate  by state applying the 1990s ;
* growth rates to the 2000s;
* assume that the weights for 2010 are the same as 2000's;
sort stnum year;
by stnum: gen lodrsup=oldrsup[_n-1];
by stnum: gen dodrsup=oldrsup-lodrsup;
by stnum: replace oldrsup=oldrsup[_n-1]+dodrsup[_n-1] if year==2009;
by stnum: gen llurate=lnurate[_n-1];
by stnum: gen durate=lnurate-llurate;
by stnum: replace lnurate=lnurate[_n-1]+durate[_n-1] if year==2009;
by stnum: replace vwgt=vwgt[_n-1] if year==2009;
**********;
**********;
reg lnpubcol lnavtui lnstapp lncolage time time2 stdum*  [weight=vwgt] ;
predict ppub;
gen enrate=exp(lnpubcol)/100.;
gen penr=exp(ppub)/100.;;
reg ygrsup ppub lnpricol oldrsup lnurate time time2 stdum* [weight=vwgt]  , robust ;
predict pygsup;
reg GAP stdum1-stdum50 time time2 oldrsup lnurate pygsup lnpricol
 [weight=vwgt] , robust ;
predict pGAP3st;
**********;
gen bavtui=-0.13;
gen bstapp=0.08;
gen bcoll=-0.6;
gen bpub=0.6;
gen bsup=-0.2;
save temp2.dta,replace;
collapse (mean) rGAP=GAP pGAP=pGAP3st  rygsup=ygrsup prsup=pygsup renr=enrate mpenr=penr
 [pweight=vwgt] , by (year);
gen lrGAP=rGAP[_n-1];
gen grGAP=(rGAP-lrGAP)/10.;
gen lpGAP=pGAP[_n-1];
gen gpGAP=(pGAP-lpGAP)/10.;
gen lygsup=rygsup[_n-1];
gen gygsup=(rygsup-lygsup)/10.;
gen lprsup=prsup[_n-1];
gen gprsup=(prsup-lprsup)/10.;
gen lrenr=renr[_n-1];
gen grenr=(ln(renr)-ln(lrenr))/10.;
gen lpenr=mpenr[_n-1];
gen gpenr=(ln(mpenr)-ln(lpenr))/10.;
di "prediction";
list year rGAP grGAP pGAP gpGAP;
list year rygsup gygsup prsup gprsup;
di "enrollment lagged 10 years";
list year renr grenr mpenr gpenr;
**********;
clear;
use temp2.dta;
* Simulation 1);
* tuition constant at 1980 level;
sort stnum;
by stnum: gen llavtui=lnavtui[_n-1];
by stnum: gen l2avtui=lnavtui[_n-2];
gen savtui=lnavtui ;
replace savtui=llavtui if year>=1999;
replace savtui=l2avtui if year>=2009;
gen spub=ppub-bavtui*lnavtui+bavtui*savtui;
gen senr=exp(spub)/100.;
gen sygsup=pygsup-bpub*ppub+bpub*spub;
gen sGAP=pGAP3st-bsup*pygsup+bsup*sygsup;
collapse (mean) msGAP=sGAP mssup=sygsup  msenr=senr
 [pweight=vwgt] , by (year);
gen lmsGAP=msGAP[_n-1];
gen gsGAP=(msGAP-lmsGAP)/10.;
gen lmssup=mssup[_n-1];
gen gmssup=(mssup-lmssup)/10.;
gen lmsenr=msenr[_n-1];
gen gmsenr=(ln(msenr)-ln(lmsenr))/10.;
di "tuition constant at 1980 level";
list year msGAP gsGAP ;
di "enrollment lagged 10 years";
list year mssup gmssup msenr gmsenr;
**********;
**********;
clear;
use temp2.dta;
**********;
* Simulation 2 ;
* No baby boom ;
* collage is lagged ten years;
* year 1989 is year 1980;
sort stnum;
by stnum: gen llcolag=lncolage[_n-1];
by stnum: gen dcolag=lncolage-llcolag;
by stnum: gen ngcolag=lncolage-dcolag;
by stnum: gen l2colag=lncolage[_n-2];
by stnum: gen l3colag=lncolage[_n-3];
gen scolage=lncolage;
replace scolage=llcolag if year>=1989;
replace scolage=l2colag if year>=1999;
replace scolage=l3colag if year>=2009;
gen spub=ppub-bcoll*lncolage+bcoll*scolage;
gen senr=exp(spub)/100.;
gen sygsup=pygsup-bpub*ppub+bpub*spub;
gen sGAP=pGAP3st-bsup*pygsup+bsup*sygsup;
collapse (mean) msGAP=sGAP mssup=sygsup  msenr=senr
 [pweight=vwgt] , by (year);
gen lmsGAP=msGAP[_n-1];
gen gsGAP=(msGAP-lmsGAP)/10.;
gen lmssup=mssup[_n-1];
gen gmssup=(mssup-lmssup)/10.;
gen lmsenr=msenr[_n-1];
gen gmsenr=(ln(msenr)-ln(lmsenr))/10.;
di "college-age held at 1970 levels";
list year msGAP gsGAP ;
di "enrollment lagged 10 years";
list year mssup gmssup msenr gmsenr;
