***Edited by Annie
version 6
clear;
***
#delimit ;
set more off;
set matsize 800;
set mem 500m;
***********;
use cpseddata.dta;
***********;
sort stnum year;
by stnum: gen time=_n;
gen time2=time*time/10;
tab stnum, gen(stdum);
***********;
count;
***********;
***********;
* regressions for Table 9 by column order ;
***********;
**Table 9, column 1;
reg GAP2 ygrsup2 odrsup2 lnurate time time2 stdum* [weight=vwgt2] , robust ;
**********;
**Table 9, column 2;
drop if lnpricol==.;
* 1st stage;
reg ygrsup2 lnpubcol lnpricol odrsup2 lnurate time time2 stdum*   [weight=vwgt2] ;
* F-test;
test lnpubcol lnpricol;
* 2SLS ;
ivreg GAP2 (ygrsup2=lnpubcol lnpricol) odrsup2 lnurate time time2 stdum* [weight=vwgt2] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol odrsup2 lnurate time time2  stdum*  [weight=vwgt2] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
***********;
**********;
**Table 9, column 3;
drop if lnstappc==.;
drop if lnavtui==.;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2  stdum*  [weight=vwgt2];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup2 ppubnc lnpricol oldrsup lnurate time time2  stdum*  [weight=vwgt2] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP2 (ygrsup2=ppubnc lnpricol) odrsup2 lnurate time time2  stdum*  [weight=vwgt2] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol odrsup2 lnurate time time2  stdum*  [weight=vwgt2] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
***********;
***********;
clear;
use cpseddata.dta;
***********;
sort stnum year;
by stnum: gen time=_n;
gen time2=time*time/10;
tab stnum, gen(stdum);
***********;
count;
***********;
**Table 9, column 4;
reg GAP3 ygrsup3 odrsup3 lnurate time time2 stdum* [weight=vwgt3] , robust ;
**********;
**Table 9, column 5;
drop if lnpricol==.;
* 1st stage;
reg ygrsup3 lnpubcol lnpricol odrsup3 lnurate time time2 stdum*   [weight=vwgt3] ;
* F-test;
test lnpubcol lnpricol;
* 2SLS ;
ivreg GAP3 (ygrsup3=lnpubcol lnpricol) odrsup3 lnurate time time2 stdum* [weight=vwgt3] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol odrsup3 lnurate time time2  stdum*  [weight=vwgt3] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
***********;
**********;
**Table 9, column 3;
drop if lnstappc==.;
drop if lnavtui==.;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2  stdum*  [weight=vwgt3];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup3 ppubnc lnpricol oldrsup lnurate time time2  stdum*  [weight=vwgt3] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP3 (ygrsup3=ppubnc lnpricol) odrsup3 lnurate time time2  stdum*  [weight=vwgt3] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol odrsup3 lnurate time time2  stdum*  [weight=vwgt3] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
