***Edited by Annie
version 6
clear;
***
#delimit ;
set more off;
set matsize 100;
***********;
use cpseddata.dta;
***********;
sort stnum year;
by stnum: gen time=_n;
gen time2=time*time/10;
tab stnum, gen(stdum);
***********;
drop if lnstappc==.;
drop if lnavtui==.;
drop if lnpricol==.;
count;
***********;
***********;
drop if lnpricol==.;
drop if lnavtui==.;
drop if lnstappc==.;
count;
save c:\proj\ed\finalpr\temp.dta,replace;
***********;
***********;
* regressions for Table 7 and 8 by sample split;
***********;
***********;
** Low Private ;
keep if perpub >0.80;
***********;
**Table 7, column 1;
**********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2 stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP (ygrsup=ppubnc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
**********;
**Table 8, column 1, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 1, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 1, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
***********;
clear;
** High Private ;
***********;
use c:\proj\ed\finalpr\temp.dta;
keep if perpub <=0.80;
***********;
**Table 7, column 2;
**********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2 stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP (ygrsup=ppubnc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
**********;
**Table 8, column 2, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 2, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 2, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol  oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
***********;
clear;
** Low CG Migration ;
***********;
use c:\proj\ed\finalpr\temp.dta;
keep if collmig <=0.18;
***********;
**Table 7, column 3;
**********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2 stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP (ygrsup=ppubnc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
**********;
**Table 8, column 3, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 3, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 3, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
***********;
clear;
** High CG Migration ;
***********;
use c:\proj\ed\finalpr\temp.dta;
keep if collmig >0.18;
***********;
**Table 7, column 4;
**********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2 stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP (ygrsup=ppubnc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
**********;
**Table 8, column 4, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 4, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 4, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
***********;
clear;
** Low Shipment ;
***********;
use c:\proj\ed\finalpr\temp.dta;
keep if export <= 0.57;
***********;
**Table 7, column 5;
**********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2 stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP (ygrsup=ppubnc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
**********;
**Table 8, column 5, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 5, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 5, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
***********;
clear;
** High Shipment ;
***********;
use c:\proj\ed\finalpr\temp.dta;
keep if export > 0.57;
***********;
**Table 7, column 6
**********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstappc time time2 stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* F-test;
test ppubnc lnpricol;
* 3-Step estimates;
ivreg GAP (ygrsup=ppubnc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
**********;
**Table 8, column 6, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 6, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 6, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
***********;
clear;
** All States ;
***********;
use c:\proj\ed\finalpr\temp.dta;
***********;
**********;
**Table 8, column 7, panel a;
***********;
reg GAP ygrsup oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
**********;
**Table 8, column 7, panel b;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
**Table 8, column 7, panel c;
***********;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstappc lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
* direct 2-SLS estimates;
ivreg GAP (ygrsup=lncolage  lnavtui lnstappc lnpricol) oldrsup lnurate time time2 stdum*  [weight=vwgt] , robust ;
***********;
