***Edited by Annie
version 6
clear;
***
#delimit ;
set matsize 800;
set more off;
use censeddata.dta;
drop if csyr>2000;
***********;
sort stnum year;
tab stnum, gen(stdum);
tab year, gen(yrdum);
**********;
***********;
* regressions for Table 10 by column order ;
***********;
**Table 10, column 1;
reg GAP ygrsup oldrsup lnurate yrdum2 yrdum3  stdum* [weight=vwgt] , robust ;
*********;
**Table 10, column 2;
*********;
drop if lnpricol==.;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*   [weight=vwgt] ;
*********;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol)  oldrsup lnurate yrdum2 yrdum3   stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
*********;
**Table 10, column 3;
* 3-Step;
drop if lnstapp==.;
drop if lnavtui==.;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstapp yrdum2 yrdum3  stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
**3rd step;
ivreg GAP (ygrsup=ppubnc lnpricol)  oldrsup lnurate yrdum2 yrdum3 stdum1-stdum50 [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
***********;
*********;
**Table 10, column 4;
* Direct 2SLS;
drop if lnstapp==.;
drop if lnavtui==.;
* 1st stage: determinants of relative supplies;
reg ygrsup lncolage lnavtui lnstapp  lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
**2SLS;
ivreg GAP (ygrsup=lncolage lnavtui lnstapp  lnpricol)  oldrsup lnurate yrdum2 yrdum3  stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lncolage lnavtui lnstapp lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
***********;
clear;
use censeddata.dta;
sort stnum year;
tab stnum, gen(stdum);
tab year, gen(yrdum);
**********;
***********;
*********;
**Table 10, column 5;
*********;
drop if lnpricol==.;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol) oldrsup yrdum2 yrdum3   stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup yrdum2 yrdum3  stdum*   [weight=vwgt] ;
*********;
***********;
*********;
**Table 10, column 6;
*********;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol lnrtrn lnrmig ) oldrsup lnurate yrdum2 yrdum3  stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol lnrtrn lnrmig oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol lnrtrn lnrmig  oldrsup lnurate yrdum2 yrdum3  stdum*   [weight=vwgt] ;
*********;
***********;
clear;
use censeddata.dta;
sort stnum year;
tab stnum, gen(stdum);
tab year, gen(yrdum);
**********;
***********;
*********;
**Table 10, column 7;
*********;
**2SLS;
ivreg GAP (ygrsup=lnrtrn lnrmig) oldrsup lnurate yrdum2 yrdum3   stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnrtrn lnrmig  oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnrtrn lnrmig  oldrsup lnurate yrdum2 yrdum3  stdum*   [weight=vwgt] ;
*********;
**Table 11, column 1;
*********;
* 1st stage;
reg ygrsup lncolage oldrsup lnurate yrdum2 yrdum3  stdum*   [weight=vwgt] ;
*********;
**2SLS;
ivreg GAP (ygrsup=lncolage)  oldrsup lnurate yrdum2 yrdum3   stdum* [weight=vwgt] , robust ;
*********;
**Table 11, column 2;
* 3-Step;
drop if lnpricol==.;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage  yrdum2 yrdum3  stdum*  [weight=vwgt];
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
**3rd step;
ivreg GAP (ygrsup=ppubnc lnpricol)  oldrsup lnurate yrdum2 yrdum3 stdum1-stdum50 [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
***********;
*********;
*********;
**Table 11, column 3;
* 3-Step;
**********;
sort stnum;
by stnum: gen lGAP=GAP[_n-1];
keep if lGAP~=.;
*********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstapp  yrdum2 yrdum3 stdum* [weight=vwgt] ;
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
**3rd step;
ivreg GAP (ygrsup=ppubnc lnpricol)  oldrsup lnurate yrdum2 yrdum3 stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo;
drop ppubnc;
*********;
**Table 11, column 4;
* 3-Step;
**********;
*********;
* 1st stage: determinants of public enrollment rates;
reg lnpubcol lncolage lnavtui lnstapp lGAP  stdum1-stdum50 yrdum2 yrdum3  [weight=vwgt] ;
predict ppubnc;
* 1st stage: determinants of relative supplies;
reg ygrsup ppubnc lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
**3rd step;
ivreg GAP (ygrsup=ppubnc lnpricol)  oldrsup lnurate yrdum2 yrdum3 stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 ppubnc lnpricol oldrsup lnurate yrdum2 yrdum3  stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ppubnc;
