#delimit ;
set more off;
set matsize 800;
set mem 500m;
***Edited by Annie;
use cpseddata.dta;
***;
***********;
sort stnum year;
by stnum: gen time=_n;
gen time2=time*time/10;
tab stnum, gen(stdum);
gen trst1=time*stdum1;
gen trst2=time*stdum2;
gen trst3=time*stdum3;
gen trst4=time*stdum4;
gen trst5=time*stdum5;
gen trst6=time*stdum6;
gen trst7=time*stdum7;
gen trst8=time*stdum8;
gen trst9=time*stdum9;
gen trst10=time*stdum10;
gen trst11=time*stdum11;
gen trst12=time*stdum12;
gen trst13=time*stdum13;
gen trst14=time*stdum14;
gen trst15=time*stdum15;
gen trst16=time*stdum16;
gen trst17=time*stdum17;
gen trst18=time*stdum18;
gen trst19=time*stdum19;
gen trst20=time*stdum20;
gen trst21=time*stdum21;
gen trst22=time*stdum22;
gen trst23=time*stdum23;
gen trst24=time*stdum24;
gen trst25=time*stdum25;
gen trst26=time*stdum26;
gen trst27=time*stdum27;
gen trst28=time*stdum28;
gen trst29=time*stdum29;
gen trst30=time*stdum30;
gen trst31=time*stdum31;
gen trst32=time*stdum32;
gen trst33=time*stdum33;
gen trst34=time*stdum34;
gen trst35=time*stdum35;
gen trst36=time*stdum36;
gen trst37=time*stdum37;
gen trst38=time*stdum38;
gen trst39=time*stdum39;
gen trst40=time*stdum40;
gen trst41=time*stdum41;
gen trst42=time*stdum42;
gen trst43=time*stdum43;
gen trst44=time*stdum44;
gen trst45=time*stdum45;
gen trst46=time*stdum46;
gen trst47=time*stdum47;
gen trst48=time*stdum48;
gen trst49=time*stdum49;
gen trst50=time*stdum50;
gen trst51=time*stdum51;
gen yr=year if year>=81;
tab yr, gen(yrd);
**constructing variables so that the year effects;
**add to zero, and are orthogonal to a time trend;
replace yrd8=yrd8-7*yrd2-6*yrd1;
replace yrd7=yrd7-6*yrd2-5*yrd1;
replace yrd6=yrd6-5*yrd2-4*yrd1;
replace yrd5=yrd5-4*yrd2-3*yrd1;
replace yrd4=yrd4-3*yrd2-2*yrd1;
replace yrd3=yrd3-2*yrd2-1*yrd1;
drop yrd2;
drop yrd1;
count;
***********;
* regressions for Table 2 by column order ;
***********;
**Table 2, column 1;
eststo:reg GAP ygrsup oldrsup lnurate time stdum* [weight=vwgt] , robust ;
**Table 2, column 2;
eststo: reg GAP ygrsup oldrsup lnurate time yrd* stdum* [weight=vwgt] , robust ;
**Table 2, column 3;
eststo owncorsup: reg GAP ygrsup oldrsup lnurate time time2 stdum* [weight=vwgt] , robust ;
**Table 2, column 4;
eststo: reg GAP ygrsup oldrsup lnurate time yrd* stdum* trst* [weight=vwgt] , robust ;
**Table 2, column 5;
eststo: reg GAP ygrsup oldrsup lnurate time time2 stdum* trst* [weight=vwgt] , robust ;
**Table 2, column 6;
eststo: reg GAP time time2 stdum*  [weight=vwgt] , robust ;
**********;
*regressions for Table 3 by column order;
***********;
**Table 3, column 1;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol)  oldrsup lnurate time stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate time stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup lnurate time stdum*   [weight=vwgt] ;
* F-test;
test lnpubcol lnpricol;
***********;
**Table 3, column 2;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol) oldrsup lnurate time yrd* stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate time yrd* stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup lnurate time yrd* stdum*   [weight=vwgt] ;
* F-test;
test lnpubcol lnpricol;
***********;
**Table 3, column 3;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol) oldrsup lnurate time time2 stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate time time2 stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup lnurate time time2 stdum*   [weight=vwgt] ;
* F-test;
test lnpubcol lnpricol;
***********;
**Table 3, column 4;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol) oldrsup lnurate time yrd* trst* stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate time yrd* trst* stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup lnurate time yrd* trst* stdum*   [weight=vwgt] ;
* F-test;
test lnpubcol lnpricol;
***********;
**Table 3, column 5;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol) oldrsup lnurate time time2 trst* stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol oldrsup lnurate time time2 trst* stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol oldrsup lnurate time time2 trst* stdum*   [weight=vwgt] ;
* F-test;
test lnpubcol lnpricol;
************;
* regressions that include interaction between time and enrollement (not shown in the paper);
************;
************;
gen tpubcol=time*lnpubcol;
gen t2pubcol=time2*lnpubcol;
gen tpricol=time*lnpricol;
gen t2pricol=time2*lnpricol;
**2SLS;
ivreg GAP (ygrsup=lnpubcol lnpricol tpubcol tpricol t2pubcol t2pricol) oldrsup lnurate
 time time2 trst* stdum* [weight=vwgt] , robust ;
**overid test;
predict res1, resid;
reg res1 lnpubcol lnpricol tpubcol tpricol t2pubcol t2pricol oldrsup lnurate
 time time2 trst* stdum*  [weight=vwgt] ;
gen chi=e(N)*e(r2);
di chi;
gen pvalo=chiprob(1,chi);
di pvalo;
drop res1 chi pvalo ;
* 1st stage;
reg ygrsup lnpubcol lnpricol tpubcol tpricol t2pubcol t2pricol oldrsup lnurate
 time time2 trst* stdum*   [weight=vwgt] ;
* F-test;
test lnpubcol lnpricol tpubcol tpricol t2pubcol t2pricol;
estout using "../results/table1.csv", cells(`"b() se() t() p()"') stats(N r2 df_m df_r df_b df) notype abbrev begin(`"""') delimiter(`"",""') end(`"""') replace;