********************************************************************************
*** Build: Soil Coverage - MapBiomas v3.0
********************************************************************************

clear
import excel using "$pathfiles_data/Originais/Mapbiomas_v3.xlsx", first // Original archive was too big; version imported is the relevant sheet with relevant years

* We will keep class 1 in general, with more detailed data on just some of them
* Level 1: 1. Floresta 2. Formação Natural não Florestal 3. Agropecuária 4. Área não Vegetada 5. Corpo D'água 6. Não Observado
* Level 2 (generated by us): 31. Agriculture;  32. Pasture; 41. Urban Infrastructure; 51. River, Lake, Ocean - all codes multiplied by 10

gen soiltype = substr(nivel1,1,1)
destring soiltype, replace

replace soiltype = 10*soiltype
replace soiltype = 31 if nivel2=="Agricultura"
replace soiltype = 32 if nivel2=="Pastagem"
replace soiltype = 41 if nivel2=="Infraestrutura Urbana"
replace soiltype = 51 if nivel2=="Rio, Lago e Oceano"

* Generate 6-digit IBGE code
tostring CODIBGE, generate(code_mun)
replace code_mun=substr(code_mun,1,6)
destring code_mun, replace

* Rename area variables
local year=2000
foreach var in I J K L M N O P Q R S{
	rename `var' area`year'
	local year = `year'+1
}

* We have to change the "direction" of years and classes (soil use), ie, we have to transpose the dataset

collapse (sum) area*, by(code_mun soiltype)
reshape long area, i(code_mun soiltype) j(year)
reshape wide area, i(code_mun year) j(soiltype)

* Missings are 0's
foreach i in 10 20 30 31 32 40 41 50 51 60{
	replace area`i'=0 if area`i'==.
}

rename area10 areaForest
rename area20 areaNatNonForest
rename area30 areaAgricOrPast
rename area31 areaAgriculture
rename area32 areaPasture
rename area40 areaOtherNonVeg
rename area41 areaUrban
rename area50 areaAquiculture
rename area51 areaWater
rename area60 areaNonObs

gen areaFarming=areaAgriculture+areaPasture+areaAgricOrPast
gen areaNonVeg=areaOtherNonVeg+areaUrban
gen areaTotalWater=areaAquiculture+areaWater


* Merge AMC information
merge m:1 code_mun using "$pathfiles_data/Originais/amcs_br.dta"


*    Result                           # of obs.
*    -----------------------------------------
*    not matched                            67
*        from master                        66  (_merge==1)
*        from using                          1  (_merge==2)
*
*    matched                            61,204  (_merge==3)
*    -----------------------------------------


* _merge==1: due to changes in municipalities (creation/merging) - e.g. Paraiso das Aguas-MS, which is a municipality effectively created after 2010 and which was created using areas from 3 other municipalities
* _merge==2: Fernando de Noronha island

keep if _merge==3
drop _merge

* Collapse by AMC year
collapse (sum) area*, by(AMC year)

save "$pathfiles_data/Workfiles/data_soil_coverage_mapbiomas_v3.dta", replace
